server:
    port: 20080

logging:
    file:
        name: /logs/lotto/lotto.log

str:
    divider: " : "

data:
    path:
        mynumber: /logs/mynumber.txt

slack:
    webhook: ${slack.webhook}

lotto:
    api: 
        url: https://www.dhlottery.co.kr/common.do?method=getLottoNumber&drwNo=
    base:
        date: 2021-01-23
        no: 947

